// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AspNetCoreGenericRepositoryPatternUnitOfWork.Entities
{
    [Table("USER_AUTHORIZATIONS")]
    public partial class UserAuthorization
    {
        [Key]
        [Column("BAKEND_MENU_ID")]
        public int BakendMenuId { get; set; }
        [Key]
        [Column("GROUPID")]
        public int Groupid { get; set; }
        [Column("ISDELETE")]
        public bool? Isdelete { get; set; }
        [Column("ISLIST")]
        public bool? Islist { get; set; }
        [Column("ISSAVE")]
        public bool? Issave { get; set; }
        [Column("ISUPDATE")]
        public bool? Isupdate { get; set; }
        [Column("CREATED", TypeName = "date")]
        public DateTime? Created { get; set; }
        [Column("MODIFIED", TypeName = "date")]
        public DateTime? Modified { get; set; }

        [ForeignKey(nameof(BakendMenuId))]
        [InverseProperty(nameof(BackendMenu.UserAuthorizations))]
        public virtual BackendMenu BakendMenu { get; set; }
        [ForeignKey(nameof(Groupid))]
        [InverseProperty(nameof(UserGroup.UserAuthorizations))]
        public virtual UserGroup Group { get; set; }
    }
}